title: Atom Network - Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.atom-net.cf
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Atom Solutions
      description: A Public Instance of RedBot
      category: Network Bots
    - name: Redux
      category: Network Bots
    - name: United Kingdom
      description: This is the service responsible for serving images, audio, and
        video. It is reliant on our CDN.
      category: Location
    - name: Meta Space
      category: Network Bots
    - name: "Atom Web "
      category: Network Utilities
      description: The Bot for Website Puropses
    - category: Network Utilities
      name: Atom Guard
    - name: Atom Website
      category: Network Utilities
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/welt_2-removebg-preview.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Network Bots
      description: This is the Bots that have been hosted by Atom Network.
      closed: false
      untitled: false
    - name: Network Utilities
      closed: false
      untitled: false
      description: The Main Bots for the Atom Net Server
    - name: Location
      description: The main servers are located here.
      closed: false
      untitled: false
    - name: Empty Category
      untitled: true
    - name: Uncategorized
      untitled: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
